/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra;

import java.awt.Color;
import java.awt.TextField;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author gerardo
 */
public class Venta extends javax.swing.JFrame {
    
    private usuarios usuarioactual;

    /**
     * Creates new form Venta
     */
    public Venta(usuarios usuario) {
        this.usuarioactual = usuario;
        initComponents();
        dibujartabla();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void dibujartabla(){
        
         DefaultTableModel v = new DefaultTableModel(new String[]{"CLIENTE","NIT","DIRECCION","TOTAL","TOTAL SIN IVA","VENDEDOR","FECHA","HORA"},ProyectoProgra.vent.size());
        jTable1.setModel(v);
        
        TableModel tabla = jTable1.getModel();
        for(int i = 0; i<ProyectoProgra.vent.size();i++){
            Vent ve = ProyectoProgra.vent.get(i);
            tabla.setValueAt(ve.cliente, i, 0);
            tabla.setValueAt(ve.nit, i, 1);
            tabla.setValueAt(ve.direc, i, 2);
            tabla.setValueAt(ve.ventafinal, i, 3);
            tabla.setValueAt(ve.ventatotalsinIva,i, 4);
            tabla.setValueAt(ve.vendedor, i, 5);
            tabla.setValueAt(ve.fecha, i, 6);
            tabla.setValueAt(ve.hora, i, 7);
                        
        }

    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("Exit");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Agregar Venta");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Actualizar Tabla");
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Exportar Ventas");
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        // TODO add your handling code here:
        AgreVenta av = new AgreVenta(usuarioactual);
        av.setVisible(true);
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        // TODO add your handling code here:
        dibujartabla();
        JOptionPane.showMessageDialog(this,"La tabla se actualizo Correctamente");
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this,"Selecciona el lugar donde quieres guardar");
        JFileChooser guardar = new JFileChooser();
        int archivo = guardar.showSaveDialog(this);
        
        if(archivo == JFileChooser.APPROVE_OPTION){
            File Ventas = guardar.getSelectedFile();
            try(FileWriter escribir = new FileWriter(Ventas + ".txt")){
                escribir.write("HISTORIAL DE VENTAS");
                escribir.write("CLIENTE | NIT | DIRECCION | TOTAL | TOTAL SIN IVA| VENDEDOR | FECHA | HORA");
                escribir.write("\n");
                for(int i = 0; i < ProyectoProgra.vent.size(); i++){
                    Vent venta = ProyectoProgra.vent.get(i);
                    escribir.write("VENTA NUM* " + (i + 1) + ":\n");
                    escribir.write(venta.cliente + " | " + venta.nit + " | " + venta.direc + " | " + venta.ventafinal + " | " + venta.ventatotalsinIva + " | " +  venta.vendedor + " | " + venta.fecha + " | " + venta.hora + " | " + "\n\n");
                   
                }
                
                JOptionPane.showMessageDialog(this,"Los datos se han descargado correctamente");
            } catch (IOException ex) {
                System.getLogger(Venta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jMenu3MenuSelected


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
